CREATE TABLE `users` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `created_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
    `user_hash` varchar(255) NOT NULL,
    `user_name_first` varchar(255) NOT NULL,
    `user_name_last` varchar(255) DEFAULT NULL,
    `user_email` varchar(255) NOT NULL,
    `user_handle` varchar(128) DEFAULT NULL,
    `user_password_hash` varchar(512) NOT NULL,
    `user_is_admin` tinyint(1) NOT NULL DEFAULT '0',
    `user_permissions` longtext DEFAULT NULL,
    `user_params` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'User params (eg subscription tiers, VIP levels, close friends, blocklist etc)' CHECK (json_valid(`user_params`)),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;


CREATE TABLE `users_unverified` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`created_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
	`user_unverified_hash` varchar(255) NOT NULL,
	`user_unverified_fp_hash` varchar(255) DEFAULT NULL,
	`user_unverified_name_first` varchar(255) NOT NULL,
	`user_unverified_name_last` varchar(255) NOT NULL,
	`user_unverified_email` varchar(255) NOT NULL,
	`user_unverified_password_hash` varchar(1024) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `log_wallet_topup` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `txn-hash` varchar(128) NOT NULL COMMENT 'Txn hash of current log entry',
 `txn-gateway` varchar(64) DEFAULT NULL,
 `txn-status_current` varchar(64) DEFAULT NULL COMMENT 'Current status of txn per log time',
 `txn-gateway_data_request` text DEFAULT NULL,
 `txn-gateway_data_response` text DEFAULT NULL,
 `txn-status_current_text` varchar(512) NOT NULL COMMENT 'Current status text of txn per log time',
 `time_created` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Log entry timestamp',
 `time_updated_last` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Timestamp of last update for current log entry',
 `comments` text NOT NULL COMMENT 'Comments / Remarks (if any)',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `wallet_topups` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `txn-hash` varchar(128) NOT NULL COMMENT 'Transaction hash (for internal reference)',
 `txn-hash_user` varchar(128) DEFAULT NULL COMMENT 'User hash attributed to the transaction',
 `txn-status` varchar(255) NOT NULL,
 `txn-status_text` mediumtext NOT NULL,
 `txn-amt_clovers` float NOT NULL DEFAULT 0 COMMENT 'Amt in clovers (virtual token currency)',
 `txn-amt_USD_cents` decimal(10,2) NOT NULL,
 `txn-time_created` timestamp NOT NULL DEFAULT current_timestamp(),
 `txn-time_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
 `txn-gateway` varchar(128) NOT NULL,
 `txn-gateway_response` longtext NOT NULL CHECK (json_valid(`txn-gateway_response`)),
 `txn-gateway_params` longtext DEFAULT NULL COMMENT 'Storage for params generated by gateway for retrieval (flexible)',
 `txn-comments` text DEFAULT NULL COMMENT 'Comments/remarks (if any)',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `wallet_transactions` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `txn-hash` varchar(128) NOT NULL COMMENT 'Transaction hash',
 `txn-hash_user` varchar(128) DEFAULT NULL COMMENT 'User hash attributed to the transaction',
 `txn-ref_id` varchar(255) DEFAULT NULL COMMENT 'Ref id of txn (e.g NOWPayments payment id, bet deduction, payout etc)',
 `txn-time_created` timestamp NOT NULL DEFAULT current_timestamp(),
 `txn-time_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
 `txn-status_latest` varchar(64) NOT NULL DEFAULT 'TXN_INITIATED',
 `txn-status_latest_text` varchar(512) DEFAULT NULL,
 `txn-amt_USD_cents` float NOT NULL DEFAULT 0 COMMENT 'Amount in cents, USD',
 `txn-amt_clovers` float NOT NULL DEFAULT 0 COMMENT 'Amt in clovers (virtual token currency)',
 `txn-comments` text DEFAULT NULL COMMENT 'Comments/remarks (if any)',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `api_keys_shippo` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`created_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
	`api_key` varchar(512) NOT NULL,
	`status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1 - active, 0 - inactive',
	`usage_count` int(11) NOT NULL DEFAULT '0' COMMENT 'Number of times this API key has been used',
	`last_used` timestamp NULL DEFAULT NULL COMMENT 'Last time this API key was used',
	PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `labels` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`created_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
	`label_hash` varchar(255) NOT NULL,
	`tracking` varchar(255) NOT NULL,
	`address_from` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'JSON object with from address',
	`address_to` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'JSON object with to address',
	`label_courier` varchar(128) NOT NULL,
	`label_params` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Label params (JSON object)' CHECK (json_valid(`label_params`)),
	`label_supplier` varchar(128) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;


CREATE TABLE `log_access` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`log_uuid` varchar(128) DEFAULT NULL,
	`requestURI` text NOT NULL,
	`protocol` varchar(16) DEFAULT NULL COMMENT 'Protocol of request, eg GET/POST/PUT etc',
	`headers` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`headers`)),
	`fp_requestID` varchar(255) DEFAULT NULL COMMENT 'Fingerprint request ID',
	`fp_visitorID` varchar(255) DEFAULT NULL COMMENT 'Fingerprint visitor ID',
	`timestamp` datetime NOT NULL DEFAULT current_timestamp(),
	`user_hash` varchar(255) DEFAULT NULL COMMENT 'User hash (if any)',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `log_errors` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`log_level` varchar(64) DEFAULT 'info' COMMENT 'Log level, ie debug/info/warning/error',
	`log_uuid` varchar(128) DEFAULT NULL,
	`log_message` text DEFAULT NULL,
	`requestURI` text NOT NULL,
	`script_path` text DEFAULT NULL COMMENT 'Path to the currently executing script',
	`protocol` varchar(16) DEFAULT NULL COMMENT 'Protocol of request, eg GET/POST/PUT etc',
	`headers` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`headers`)),
	`params_GET` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`params_GET`)),
	`params_POST` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`params_POST`)),
	`fp_requestID` varchar(255) DEFAULT NULL COMMENT 'Fingerprint request ID',
	`fp_visitorID` varchar(255) DEFAULT NULL COMMENT 'Fingerprint visitor ID',
	`timestamp` datetime NOT NULL DEFAULT current_timestamp(),
	`user_hash` varchar(255) DEFAULT NULL COMMENT 'User hash (if any)',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `address_lookup` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `address_hash` varchar(64) NOT NULL,
  `record_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `record_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lookup_provider` varchar(50) NOT NULL,
  `address_line_1` varchar(255) NOT NULL,
  `address_line_2` varchar(255) DEFAULT NULL,
  `address_line_3` varchar(255) DEFAULT NULL,
  `city_locality` varchar(100) NOT NULL,
  `state_province` varchar(100) NOT NULL,
  `postal_code` varchar(20) NOT NULL,
  `country_code` varchar(2) NOT NULL,
  `address_type` varchar(20) DEFAULT NULL,
  `lookup_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`lookup_data`)),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;