CREATE TABLE `users` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `created_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
    `user_hash` varchar(255) NOT NULL,
    `user_name_first` varchar(255) NOT NULL,
    `user_name_last` varchar(255) DEFAULT NULL,
    `user_email` varchar(255) NOT NULL,
    `user_handle` varchar(128) DEFAULT NULL,
    `user_password_hash` varchar(512) NOT NULL,
    `user_is_admin` tinyint(1) NOT NULL DEFAULT '0',
    `user_permissions` longtext DEFAULT NULL,
    `user_params` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'User params (eg subscription tiers, VIP levels, close friends, blocklist etc)' CHECK (json_valid(`user_params`)),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `users_unverified` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `created_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
    `user_unverified_hash` varchar(255) NOT NULL,
    `user_unverified_fp_hash` varchar(255) DEFAULT NULL,
    `user_unverified_name_first` varchar(255) NOT NULL,
    `user_unverified_name_last` varchar(255) NOT NULL,
    `user_unverified_email` varchar(255) NOT NULL,
    `user_unverified_password_hash` varchar(1024) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `log_wallet_topup` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `txn-hash` varchar(128) NOT NULL COMMENT 'Txn hash of current log entry',
    `txn-gateway` varchar(64) DEFAULT NULL,
    `txn-status_current` varchar(64) DEFAULT NULL COMMENT 'Current status of txn per log time',
    `txn-gateway_data_request` text DEFAULT NULL,
    `txn-gateway_data_response` text DEFAULT NULL,
    `txn-status_current_text` varchar(512) NOT NULL COMMENT 'Current status text of txn per log time',
    `time_created` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Log entry timestamp',
    `time_updated_last` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Timestamp of last update for current log entry',
    `comments` text NOT NULL COMMENT 'Comments / Remarks (if any)',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `wallet_topups` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `txn-hash` varchar(128) NOT NULL COMMENT 'Transaction hash (for internal reference)',
    `txn-hash_user` varchar(128) DEFAULT NULL COMMENT 'User hash attributed to the transaction',
    `txn-status` varchar(255) NOT NULL,
    `txn-status_text` mediumtext NOT NULL,
    `txn-amt_shiptokens` float NOT NULL DEFAULT 0 COMMENT 'Amt in shiptokens (virtual token currency)',
    `txn-amt_USD_cents` decimal(10, 2) NOT NULL,
    `txn-time_created` timestamp NOT NULL DEFAULT current_timestamp(),
    `txn-time_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    `txn-gateway` varchar(128) NOT NULL,
    `txn-gateway_response` longtext DEFAULT NULL,
    `txn-gateway_params` longtext DEFAULT NULL COMMENT 'Storage for params generated by gateway for retrieval (flexible)',
    `txn-comments` text DEFAULT NULL COMMENT 'Comments/remarks (if any)',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 2 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `wallet_transactions` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `txn_category` varchar(64) DEFAULT NULL COMMENT 'Category of transaction (eg bet, bet_payout, adjustment, topup etc)',
    `txn-hash` varchar(128) DEFAULT NULL,
    `txn-hash_user` varchar(128) DEFAULT NULL COMMENT 'User hash attributed to the transaction',
    `txn-ref_id` varchar(255) DEFAULT NULL COMMENT 'Ref id of txn (e.g NOWPayments payment id, bet deduction, payout etc)',
    `txn-time_created` timestamp NOT NULL DEFAULT current_timestamp(),
    `txn-time_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    `txn-status_latest` varchar(64) NOT NULL DEFAULT 'TXN_INITIATED',
    `txn-status_latest_text` varchar(512) DEFAULT NULL,
    `txn-amt_USD_cents` float NOT NULL DEFAULT 0 COMMENT 'Amount in cents, USD',
    `txn-amt_shiptokens` float NOT NULL DEFAULT 0 COMMENT 'Amt in shiptokens (virtual token currency)',
    `txn-comments` text DEFAULT NULL COMMENT 'Comments/remarks (if any)',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- A trigger to generate a unique transaction hash for new records in the `wallet_transactions` table.
DELIMITER $$

CREATE TRIGGER `generate_txn_hash`
BEFORE INSERT ON `wallet_transactions`
FOR EACH ROW
BEGIN
    -- Declare variables
    DECLARE new_txn_hash VARCHAR(128);
    DECLARE category_camel_case VARCHAR(64);

    -- Convert the category to camel case and remove spaces and special characters
    SET category_camel_case = REPLACE(NEW.`txn_category`, ' ', ''); -- Remove spaces
    SET category_camel_case = LOWER(category_camel_case); -- Convert to lowercase
    SET category_camel_case = CONCAT(UPPER(SUBSTR(category_camel_case, 1, 1)), SUBSTR(category_camel_case, 2)); -- Capitalize the first letter

    -- Generate a unique hash
    SET new_txn_hash = CONCAT('txn_', category_camel_case, '_', MD5(UUID()));

    -- Set the new transaction hash
    SET NEW.`txn-hash` = new_txn_hash;
END$$

DELIMITER;





CREATE TABLE `api_keys_shippo` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `created_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
    `api_key` varchar(512) NOT NULL,
    `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1 - active, 0 - inactive',
    `usage_count` int(11) NOT NULL DEFAULT '0' COMMENT 'Number of times this API key has been used',
    `last_used` timestamp NULL DEFAULT NULL COMMENT 'Last time this API key was used',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `log_access` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `log_uuid` varchar(128) DEFAULT NULL,
    `requestURI` text NOT NULL,
    `protocol` varchar(16) DEFAULT NULL COMMENT 'Protocol of request, eg GET/POST/PUT etc',
    `headers` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`headers`)),
    `params_GET` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
    `params_POST` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
    `fp_requestID` varchar(255) DEFAULT NULL COMMENT 'Fingerprint request ID',
    `fp_visitorID` varchar(255) DEFAULT NULL COMMENT 'Fingerprint visitor ID',
    `timestamp` datetime NOT NULL DEFAULT current_timestamp(),
    `user_hash` varchar(255) DEFAULT NULL COMMENT 'User hash (if any)',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- A trigger to generate a unique transaction hash for new records in the `log_errors` table.
DELIMITER $$

CREATE TRIGGER `generate_log_access_hash`
BEFORE INSERT ON `log_access`
FOR EACH ROW
BEGIN

	DECLARE new_txn_hash VARCHAR(128);

	
    -- Generate a unique hash
    SET new_txn_hash = CONCAT('log_access_', MD5(UUID()));

    -- Set the new transaction hash
    SET NEW.`log_uuid` = new_txn_hash;
END$$

DELIMITER;

CREATE TABLE `log_errors` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `log_level` varchar(64) DEFAULT 'info' COMMENT 'Log level, ie debug/info/warning/error',
    `log_uuid` varchar(128) DEFAULT NULL,
    `log_message` text DEFAULT NULL,
    `requestURI` text NOT NULL,
    `script_path` text DEFAULT NULL COMMENT 'Path to the currently executing script',
    `protocol` varchar(16) DEFAULT NULL COMMENT 'Protocol of request, eg GET/POST/PUT etc',
    `headers` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`headers`)),
    `params_GET` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`params_GET`)),
    `params_POST` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`params_POST`)),
    `fp_requestID` varchar(255) DEFAULT NULL COMMENT 'Fingerprint request ID',
    `fp_visitorID` varchar(255) DEFAULT NULL COMMENT 'Fingerprint visitor ID',
    `timestamp` datetime NOT NULL DEFAULT current_timestamp(),
    `user_hash` varchar(255) DEFAULT NULL COMMENT 'User hash (if any)',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- A trigger to generate a unique transaction hash for new records in the `log_errors` table.
-- DELIMITER $$
-- CREATE TRIGGER `generate_txn_hash`
-- BEFORE INSERT ON `log_errors`
-- FOR EACH ROW
-- BEGIN
--     -- Declare variables
--     DECLARE new_txn_hash VARCHAR(128);
--     DECLARE category_camel_case VARCHAR(64);

--     -- Convert the category to camel case and remove spaces and special characters
--     SET category_camel_case = REPLACE(NEW.`txn_category`, ' ', ''); -- Remove spaces
--     SET category_camel_case = LOWER(category_camel_case); -- Convert to lowercase
--     SET category_camel_case = CONCAT(UPPER(SUBSTR(category_camel_case, 1, 1)), SUBSTR(category_camel_case, 2)); -- Capitalize the first letter

--     -- Generate a unique hash
--     SET new_txn_hash = CONCAT('txn_', category_camel_case, '_', MD5(UUID()));

--     -- Set the new transaction hash
--     SET NEW.`txn-hash` = new_txn_hash;
-- END$$
-- DELIMITER ;

CREATE TABLE `addresses_customer` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `user_hash` varchar(255) NOT NULL,
    `address_uuid` varchar(128) NOT NULL,
    `address_label` varchar(255) DEFAULT NULL,
    `address_name` varchar(255) DEFAULT NULL,
    `address_line_1` varchar(255) NOT NULL,
    `address_line_2` varchar(255) DEFAULT NULL,
    `address_line_3` varchar(255) DEFAULT NULL,
    `city_locality` varchar(100) NOT NULL,
    `state_province` varchar(100) NOT NULL,
    `postal_code` varchar(20) NOT NULL,
    `country_code` varchar(2) NOT NULL,
    `address_type` varchar(20) DEFAULT NULL,
    `created_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    `address_params` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Additional address params (JSON object)' CHECK (json_valid(`address_params`)),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- A trigger to generate a unique address UUID for new records in the `addresses_customer` table.
DELIMITER $$

CREATE TRIGGER `generate_address_uuid`
BEFORE INSERT ON `addresses_customer`
FOR EACH ROW
BEGIN
    SET NEW.`address_uuid` = CONCAT('addr_', LOWER(HEX(UUID())));
END$$

DELIMITER;

CREATE TABLE `address_lookup` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `address_hash` varchar(64) NOT NULL,
    `record_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `record_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `lookup_provider` varchar(50) NOT NULL,
    `address_line_1` varchar(255) NOT NULL,
    `address_line_2` varchar(255) DEFAULT NULL,
    `address_line_3` varchar(255) DEFAULT NULL,
    `city_locality` varchar(100) NOT NULL,
    `state_province` varchar(100) NOT NULL,
    `postal_code` varchar(20) NOT NULL,
    `country_code` varchar(2) NOT NULL,
    `address_type` varchar(20) DEFAULT NULL,
    `lookup_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`lookup_data`)),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE `shipment_quotations` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `quote_uuid` varchar(128) DEFAULT NULL,
    `address_from` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'JSON object with from address',
    `address_from_country` varchar(2) NOT NULL COMMENT 'Country code of from address (ISO 3166-1 alpha-2)',
    `address_to` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'JSON object with to address',
    `address_to_country` varchar(2) NOT NULL COMMENT 'Country code of to address (ISO 3166-1 alpha-2)',
    `parcel_details` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'JSON object with parcel details',
    `rate_price_cents` int(11) DEFAULT NULL,
    `rate_currency` varchar(8) DEFAULT NULL,
    `rate_provider` varchar(128) DEFAULT NULL COMMENT 'Shipping rate provider (e.g Shippo, EasyPost etc)',
    `service_level` varchar(128) DEFAULT NULL COMMENT 'Service level name (e.g. USPS Priority Mail)',
    `created_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    `quote_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Full quotation data (JSON object)' CHECK (json_valid(`quote_data`)),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- A trigger to generate a unique quote UUID for new records in the `shipment_quotations` table.
DELIMITER $$

CREATE TRIGGER `generate_quote_uuid`
BEFORE INSERT ON `shipment_quotations`
FOR EACH ROW
BEGIN
    -- Declare variables
    DECLARE new_quote_uuid VARCHAR(128);
    DECLARE rate_provider_camel_case VARCHAR(64);

	-- Convert the rate provider to camel case and remove spaces and special characters
	SET rate_provider_camel_case = REPLACE(NEW.`rate_provider`, ' ', ''); -- Remove spaces
	SET rate_provider_camel_case = LOWER(rate_provider_camel_case); -- Convert to lowercase
	SET rate_provider_camel_case = CONCAT(UPPER(SUBSTR(rate_provider_camel_case, 1, 1)), SUBSTR(rate_provider_camel_case, 2)); -- Capitalize the first letter

	-- Generate a unique hash UUID
	SET new_quote_uuid = CONCAT('quote_', rate_provider_camel_case, '_', md5(UUID()));

    -- Set the new quote UUID
    SET NEW.`quote_uuid` = new_quote_uuid;
END$$

DELIMITER;

CREATE TABLE `labels_generated` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `label_uuid` varchar(128) DEFAULT NULL,
    `quote_uuid` varchar(128) DEFAULT NULL,
    `address_from_uuid` varchar(128) DEFAULT NULL COMMENT 'UUID of from address used for label (from addresses_customer table)',
    `address_to_uuid` varchar(128) DEFAULT NULL COMMENT 'UUID of to address used for label (to addresses_customer table)',
    `created_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    `tracking` varchar(255) DEFAULT NULL,
    `courier_name` varchar(128) DEFAULT NULL,
    `courier_service_level` varchar(128) DEFAULT NULL,
    `label_params_log` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Label params (JSON object)' CHECK (
        json_valid(`label_params_log`)
    ),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- A trigger to generate a unique label UUID for new records in the `labels_generated` table.
-- label_uuid format: label_[courierName]_[tracking]_[timestamp from created_timestamp]

DELIMITER $$

CREATE TRIGGER `generate_label_uuid`
BEFORE INSERT ON `labels_generated`
FOR EACH ROW
BEGIN
    -- Declare variables
    DECLARE new_label_uuid VARCHAR(128);
    DECLARE courier_name_camel_case VARCHAR(64);
    DECLARE tracking_camel_case VARCHAR(64);

	-- Convert the courier name and tracking to camel case and remove spaces and special characters
	SET courier_name_camel_case = REPLACE(NEW.`courier_name`, ' ', ''); -- Remove spaces
	SET courier_name_camel_case = LOWER(courier_name_camel_case); -- Convert to lowercase
	SET courier_name_camel_case = CONCAT(UPPER(SUBSTR(courier_name_camel_case, 1, 1)), SUBSTR(courier_name_camel_case, 2)); -- Capitalize the first letter

	SET tracking_camel_case = REPLACE(NEW.`tracking`, ' ', ''); -- Remove spaces
	SET tracking_camel_case = LOWER(tracking_camel_case); -- Convert to lowercase
	SET tracking_camel_case = CONCAT(UPPER(SUBSTR(tracking_camel_case, 1, 1)), SUBSTR(tracking_camel_case, 2)); -- Capitalize the first letter

	-- Generate a unique hash UUID
	SET new_label_uuid = CONCAT('label_', courier_name_camel_case, '_', tracking_camel_case, '_', UNIX_TIMESTAMP(NEW.`created_timestamp`));

    -- Set the new label UUID
    SET NEW.`label_uuid` = new_label_uuid;
END$$

DELIMITER;