<?php

// Require the betting class
require_once(realpath(__DIR__ . '/class_betting.php'));

// Require the user wallet class
require_once(realpath(__DIR__ . '/class_user_wallet.php'));

// Require the user class
require_once(realpath(__DIR__ . '/class_user.php'));

class class_betting_coinflip extends class_betting {

	private $class_user_wallet;
	private $class_user;
	// Initialize classes

	public function __construct() {
		parent::__construct();
		$this->class_user_wallet = new class_user_wallet();
		$this->class_user = new class_user();
	}

	/* Coin flip game:

		Coin flip game is a simple game where the user bets on the outcome of a coin flip.
		The user can bet on either heads or tails.
		The user can bet a certain amount of clovers.
		The user can win or lose the bet based on the outcome of the coin flip.

		Payout is 2 to 1. If the user wins, they receive 2 clovers for every 1 clover they bet.



		User params required:
		server_seed - The server seed for the game. This is server side generated and is fixed per game.
		player_seed - The player seed for the game. This is client side generated.
		player_bet - The player bet. This is the amount of clovers the player is betting.
		player_bet_choice - The player bet choice. This is the choice the player is betting on. (heads or tails)


		Additional params required:
		nonce - The nonce for the game. This is used to ensure the game is unique and not replayed.
				Nonce is generated by the server based on the player's bet history and other factors.
				It will directly affect the outcome of the game.


		For now, we disregard all params and generate a fixed outcome based on house odds 52 and 48.
		52% house will win regardless of the player's bet. i.e: If player bets heads, the outcome will be tails with 52% probability.

		#TODO Implement the actual betting logic and payout logic.






		Table: bets_coinflip

		CREATE TABLE `bets_coinflip` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`bet_hash` varchar(128) DEFAULT NULL,
		`bet_player_hash` varchar(128) DEFAULT NULL,
		`bet_date_created` timestamp NOT NULL DEFAULT current_timestamp(),
		`bet_date_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
		`bet_server_seed` varchar(128) DEFAULT NULL,
		`bet_player_seed` varchar(128) DEFAULT NULL,
		`bet_nonce` varchar(255) DEFAULT NULL COMMENT 'Nonce generated for current bet session',
		`bet_params` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Any special betting parameters' CHECK (json_valid(`bet_params`)),
		`bet_ledger_log` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`bet_ledger_log`)),
		`bet_amount` float NOT NULL DEFAULT 0,
		`bet_outcomes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'JSON array of bet outcomes' CHECK (json_valid(`bet_outcomes`)),
		`bet_payouts` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'JSON array of bet payouts per player' CHECK (json_valid(`bet_payouts`)),
		`bet_comments` text DEFAULT NULL COMMENT 'bet comments (if any)',
		PRIMARY KEY (`id`)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
		

	*/


	private function generate_nonce($user_hash) {
		// Get the user's betting stats
		// $user_stats = $this->get_player_betting_stats($user_hash);



		// For now, placeholder nonce
		$nonce = bin2hex(random_bytes(32));

		return $nonce;
	}


	// Get coinflip betting stats
	/* Stats to track (grouped to all time, last 24 hours, last 7 days, last 30 days, last 10 bets, last 100 bets):

		Total bet count
		Total bet amount (clovers)

		Total win count
		Total win amount (clovers)

		Total loss count
		Total loss amount (clovers)

		Total payout amount (clovers)

		Win rate
		Loss rate

		Average bet amount (clovers)
		Average win amount (clovers)
		Average loss amount (clovers)

		


	*/
	public function get_coinflip_betting_stats($user_hash) {
		
		// Build the return array
		$return_array = array(
			"all_time" => [	'total_bet_count' => 0,
							'total_bet_amount' => 0, 
							'total_win_count' => 0, 
							'total_win_amount' => 0, 
							'total_loss_count' => 0, 
							'total_loss_amount' => 0, 
							'total_payout_amount' => 0, 
							'win_rate' => 0, 
							'loss_rate' => 0, 
							'average_bet_amount' => 0, 
							'average_win_amount' => 0, 
							'average_loss_amount' => 0
						],
			"last_24_hours" => [	'total_bet_count' => 0,
									'total_bet_amount' => 0, 
									'total_win_count' => 0, 
									'total_win_amount' => 0, 
									'total_loss_count' => 0, 
									'total_loss_amount' => 0, 
									'total_payout_amount' => 0, 
									'win_rate' => 0, 
									'loss_rate' => 0, 
									'average_bet_amount' => 0, 
									'average_win_amount' => 0, 
									'average_loss_amount' => 0
								],
			"last_7_days" => [	'total_bet_count' => 0,
									'total_bet_amount' => 0, 
									'total_win_count' => 0, 
									'total_win_amount' => 0, 
									'total_loss_count' => 0, 
									'total_loss_amount' => 0, 
									'total_payout_amount' => 0, 
									'win_rate' => 0, 
									'loss_rate' => 0, 
									'average_bet_amount' => 0, 
									'average_win_amount' => 0, 
									'average_loss_amount' => 0
								],
			"last_30_days" => [	'total_bet_count' => 0,
									'total_bet_amount' => 0, 
									'total_win_count' => 0, 
									'total_win_amount' => 0, 
									'total_loss_count' => 0, 
									'total_loss_amount' => 0, 
									'total_payout_amount' => 0, 
									'win_rate' => 0, 
									'loss_rate' => 0, 
									'average_bet_amount' => 0, 
									'average_win_amount' => 0, 
									'average_loss_amount' => 0
								],
			"last_10_bets" => [	'total_bet_count' => 0,
									'total_bet_amount' => 0, 
									'total_win_count' => 0, 
									'total_win_amount' => 0, 
									'total_loss_count' => 0, 
									'total_loss_amount' => 0, 
									'total_payout_amount' => 0, 
									'win_rate' => 0, 
									'loss_rate' => 0, 
									'average_bet_amount' => 0, 
									'average_win_amount' => 0, 
									'average_loss_amount' => 0
								],
			"last_100_bets" => [	'total_bet_count' => 0,
									'total_bet_amount' => 0, 
									'total_win_count' => 0, 
									'total_win_amount' => 0, 
									'total_loss_count' => 0, 
									'total_loss_amount' => 0, 
									'total_payout_amount' => 0, 
									'win_rate' => 0, 
									'loss_rate' => 0, 
									'average_bet_amount' => 0, 
									'average_win_amount' => 0, 
									'average_loss_amount' => 0
								]
		);

		// Get the stats from the database
		$query_stats = "SELECT * FROM bets_coinflip
						WHERE bet_player_hash = :user_hash
						ORDER BY bet_date_created DESC";

		// The query params
		$query_params = array(
			':user_hash' => $user_hash
		);

		// Execute the query
		try {
			$stmt = $this->db->prepare($query_stats);
			$stmt->execute($query_params);
			$stats = $stmt->fetchAll(PDO::FETCH_ASSOC);
		} catch (Exception $e) {
			$this->add_error('Error getting coinflip betting stats', 'error');
			return $return_array;
		}

		// Process the stats
		foreach ($stats as $stat) {
			// Get the bet date created
			$bet_date_created = $stat['bet_date_created'];

			// Get the bet amount
			$bet_amount_clovers = $stat['bet_amount'];

			// Get the bet outcomes
			$bet_outcomes = json_decode($stat['bet_outcomes'], true);

			// Get the bet payouts
			$bet_payouts = json_decode($stat['bet_payouts'], true);

			// Get the bet outcome win/loss
			$bet_outcome_win = $bet_outcomes['player_bet_outcome'];

			// Get the bet payout
			$bet_payout = $bet_payouts['player_payout'];


			// Populate the return array stats
			









		}



		// Return the return array
		return $return_array;

	}


	public function place_bet($player_bet_amount_clovers, $player_seed, $player_bet_choice, $user_hash = null) {

		// House edge is 52%
		$house_edge = 0.52;

		// If user hash is not provided, use the SESSION user hash
		if ($user_hash === null) {
			$user_hash = $_SESSION['user_hash'];
		}

		// Ensure user hash is valid
		if (!$this->class_user->check_user_hash_exists($user_hash)) {
			$this->add_error('User hash not found', 'warning');
			return false;
		}

		// Generate a bet hash based on the user hash and the current timestamp
		$bet_hash = 'bet_coinflip_' . hash('sha256', $user_hash . time());

		// Return array
		$return_array = array(
			"success" => false,
			"outcome" => "",
			"payout" => 0
		);



		// Get the params for the bet
		$server_seed = $this->get_server_seed($user_hash);
		$nonce = $this->generate_nonce($user_hash);

		// Verify that the player has enough clovers to bet
		if ($this->class_user_wallet->get_user_wallet_balance_amt_clovers($user_hash) < $player_bet_amount_clovers) {
			$this->add_error('You do not have enough clovers to bet', 'warning');
			return $return_array;
		}

		// Ensure the bet choice is valid
		if ($player_bet_choice !== 'heads' && $player_bet_choice !== 'tails') {
			$this->add_error('Invalid bet choice', 'warning');
			return $return_array;
		}

		// Ensure the bet amount is greater than 0
		if ($player_bet_amount_clovers <= 0) {
			$this->add_error('Bet amount must be greater than 0', 'warning');
			return $return_array;
		}


		// Get a random decimal between 0 and 1
		$outcome_decimal = mt_rand() / mt_getrandmax();

		// If the outcome is less than the house edge, the house wins
		if ($outcome_decimal < $house_edge) {
			if ($player_bet_choice === 'heads') {
				$outcome = 'tails'; // House wins
			} else {
				$outcome = 'heads'; // House wins
			}
		} else {
			// The player wins
			if ($player_bet_choice === 'heads') {
				$outcome = 'heads';
			} else {
				$outcome = 'tails';
			}
		}

		// Player bet outcome (win = 1, loss = 0)
		$player_bet_outcome = ($outcome === $player_bet_choice) ? 1 : 0;

		// Calculate the player's win or loss based on the outcome
		if ($player_bet_outcome === 1) {
			$player_win_loss = $player_bet_amount_clovers * 2;
		} else {
			$player_win_loss = $player_bet_amount_clovers * -1;
		}


		// Build the bet params array
		$bet_params = array(
			'server_seed' => $server_seed,
			'nonce' => $nonce,
			'player_seed' => $player_seed,
			'player_bet_amount_clovers' => $player_bet_amount_clovers,
			'player_bet_choice' => $player_bet_choice
		);

		// Build the bet outcomes array
		$bet_outcomes = array(
			'outcome' => $outcome,
			'outcome_decimal' => $outcome_decimal,
			'player_bet_outcome' => $player_bet_outcome
		);

		// Build the bet payouts array
		$bet_payouts = array(
			'player_payout' => $player_win_loss
		);



		// Store the bet in the database
		$query_bet_outcome = "INSERT INTO bets_coinflip (
											bet_hash, 
											bet_player_hash, 
											bet_server_seed, 
											bet_player_seed, 
											bet_nonce, 
											bet_params, 
											bet_amount, 
											bet_outcomes, 
											bet_payouts)
									VALUES (
											:bet_hash,
											:bet_player_hash,
											:bet_server_seed,
											:bet_player_seed,
											:bet_nonce,
											:bet_params,
											:bet_amount,
											:bet_outcomes,
											:bet_payouts
											)";


		// Query params
		$query_params = array(
			':bet_hash' => $bet_hash,
			':bet_player_hash' => $user_hash,
			':bet_server_seed' => $server_seed,
			':bet_player_seed' => $player_seed,
			':bet_nonce' => $nonce,
			':bet_params' => json_encode($bet_params),
			':bet_amount' => $player_bet_amount_clovers,
			':bet_outcomes' => json_encode($bet_outcomes),
			':bet_payouts' => json_encode($bet_payouts)
		);

		// Execute the query
		try {
			$stmt = $this->db->prepare($query_bet_outcome);
			$stmt->execute($query_params);
		} catch (Exception $e) {
			$this->add_error('Error placing bet', 'error');
			return $return_array;
		}

		// Store the bet record in the ledger
		$this->store_bet_record_in_ledger($bet_hash, 'coinflip', $user_hash, $player_bet_amount_clovers, $player_bet_outcome, $player_win_loss);

		// Return the outcome and payout
		$return_array['success'] = true;
		$return_array['outcome'] = $outcome;
		$return_array['payout'] = $player_win_loss;

		return $return_array;
	}
}
