<?php

$autoloadPath = realpath(__DIR__ . '/../vendor/autoload.php');

if (file_exists($autoloadPath)) {
	require_once($autoloadPath);
} else {
	die('Autoload file not found');
}

// Require main class
require_once(realpath(__DIR__ . '/class_main.php'));

// Require user class
require_once(realpath(__DIR__ . '/class_user.php'));

// Require gateway classes
require_once(realpath(__DIR__ . '/class_gateway_crypto_nowpayments.php'));





/* CREATE TABLE `wallet_topups` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `txn-hash` varchar(128) NOT NULL COMMENT 'Transaction hash (for internal reference)',
 `txn-hash_user` varchar(128) DEFAULT NULL COMMENT 'User hash attributed to the transaction',
 `txn-status` varchar(255) NOT NULL,
 `txn-status_text` mediumtext NOT NULL,
 `txn-amt_USD_cents` decimal(10,2) NOT NULL,
 `txn-time_created` timestamp NOT NULL DEFAULT current_timestamp(),
 `txn-time_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
 `txn-gateway` varchar(128) NOT NULL,
 `txn-gateway_response` longtext NOT NULL CHECK (json_valid(`txn-gateway_response`)),
 `txn-gateway_params` longtext DEFAULT NULL COMMENT 'Storage for params generated by gateway for retrieval (flexible)',
 `txn-comments` text DEFAULT NULL COMMENT 'Comments/remarks (if any)',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `wallet_transactions` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `txn-hash` varchar(128) NOT NULL COMMENT 'Transaction hash',
 `txn-hash_user` varchar(128) DEFAULT NULL COMMENT 'User hash attributed to the transaction',
 `txn-ref_id` varchar(255) DEFAULT NULL COMMENT 'Ref id of txn (e.g NOWPayments payment id, bet deduction, payout etc)',
 `txn-time_created` timestamp NOT NULL DEFAULT current_timestamp(),
 `txn-time_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
 `txn-status_latest` varchar(64) NOT NULL DEFAULT 'TXN_INITIATED',
 `txn-status_latest_text` varchar(512) DEFAULT NULL,
 `txn-amt_USD_cents` float NOT NULL DEFAULT 0 COMMENT 'Amount in cents, USD',
 `txn-comments` text DEFAULT NULL COMMENT 'Comments/remarks (if any)',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- A trigger to generate a unique transaction hash for new records in the `wallet_transactions` table.
DELIMITER $$
CREATE TRIGGER `generate_txn_hash`
BEFORE INSERT ON `wallet_transactions`
FOR EACH ROW
BEGIN
    -- Declare variables
    DECLARE new_txn_hash VARCHAR(128);
    DECLARE category_camel_case VARCHAR(64);

    -- Convert the category to camel case and remove spaces and special characters
    SET category_camel_case = REPLACE(NEW.`txn_category`, ' ', ''); -- Remove spaces
    SET category_camel_case = LOWER(category_camel_case); -- Convert to lowercase
    SET category_camel_case = CONCAT(UPPER(SUBSTR(category_camel_case, 1, 1)), SUBSTR(category_camel_case, 2)); -- Capitalize the first letter

    -- Generate a unique hash
    SET new_txn_hash = CONCAT('txn_', category_camel_case, '_', MD5(UUID()));

    -- Set the new transaction hash
    SET NEW.`txn-hash` = new_txn_hash;
END$$
DELIMITER ;








/* Some txn-status_latest values:

	PAYMENT_INITIATED
	PENDING_PAYMENT
	PAYMENT_COMPLETED
	FAILED_PAYMENT
	TIMEOUT_CANCELLED
	CANCELLED_PAYMENT
	VOIDED_PAYMENT

*/


/* The user's wallet balance is broken down into a few categories:

	1. Available balance for spending
	2. Pending balance (for pending transactions)
	3. Withdrawable balance (for withdrawals into fiat or crypto)


	1. Available balance for spending
	This is the balance that the user can use to place bets.

	2. Pending balance
	This is the balance that is pending settlements (eg from bets, unprocessed payouts, etc)

	3. Withdrawable balance
	This is the balance that the user can withdraw into fiat or crypto.
	Withdrawable balance should not include balances that were derived from topups due to AML.

*/


class class_user_wallet extends class_main {

	// Initialize classes
	private $class_gateway_crypto_nowpayments;
	private $class_user;

	public function __construct() {
		parent::__construct();
		$this->class_gateway_crypto_nowpayments = new class_gateway_crypto_nowpayments();
		$this->class_user = new class_user();
	}

	public function __destruct() {
		parent::__destruct();
	}

	// Get the user's wallet balance
	public function get_user_wallet_balance_amt_usd($user_hash) {

		// Variables
		$total_usd = 0.00;
		$total_topups = 0.00;
		$total_purchases = 0.00;
		$total_adjustments = 0.00;

		// Ensure user hash is valid
		if (!$this->class_user->check_user_hash_exists($user_hash)) {
			$this->add_error('User hash not found', 'warning');
			return 0.00;
		}

		// Get all wallet transactions for the user from the wallet_topups database
		// Only include completed transactions
		$query_topups = "SELECT
					SUM(`txn-amt_usd_cents`) AS `txn-amt_usd_cents`
				FROM wallet_topups
				WHERE `txn-hash_user` = :userhash
				AND `txn-status` = 'PAYMENT_COMPLETED'
				";

		// The parameter values
		$query_params_topups = array(
			':userhash' => $user_hash,
		);

		// Execute the query
		try {
			$stmt_topups = $this->db->prepare($query_topups);
			$stmt_topups->execute($query_params_topups);
			$result_topups = $stmt_topups->fetch(PDO::FETCH_ASSOC);

			if ($result_topups['txn-amt_usd_cents']) {
				// The total amount of USD
				$total_topups = $result_topups['txn-amt_usd_cents'];
			}
		} catch (PDOException $e) {
			$this->add_error($e->getMessage(), 'error');
			return 0.00;
		}

		// TODO $total_purchases calculation can be added here when purchase functionality is implemented

		// Get all adjustments from wallet_transactions database
		$query_adjustments = "SELECT
								SUM(`txn-amt_usd_cents`) AS `txn-amt_usd_cents`
							FROM wallet_transactions
							WHERE `txn-hash_user` = :userhash
							AND `txn-category` = 'adjustment'
							";
							
		// The parameter values
		$query_params_adjustments = array(
			':userhash' => $user_hash,
		);

		// Execute the query
		try {
			$stmt_adjustments = $this->db->prepare($query_adjustments);
			$stmt_adjustments->execute($query_params_adjustments);
			$result_adjustments = $stmt_adjustments->fetch(PDO::FETCH_ASSOC);

			if ($result_adjustments['txn-amt_usd_cents']) {
				// The total amount of adjustments
				$total_adjustments = $result_adjustments['txn-amt_usd_cents'];
			}
		} catch (PDOException $e) {
			$this->add_error($e->getMessage(), 'error');
			return 0.00;
		}

		// Calculate the final wallet balance
		$final_wallet_balance = $total_topups - $total_purchases + $total_adjustments;

		// Return the total amount in USD cents
		return $final_wallet_balance;
	}


	// Get the user's wallet balance details
	// 1. Available balance for spending = total_topups - total_withdrawals + total_bet_payouts
	// 2. Withdrawable balance = (total_bet_payouts - total_withdrawals) - total_topups (Any USD from topups are not withdrawable)
	public function get_user_wallet_balance_details($user_hash) {

		// Ensure user hash is valid
		if (!$this->class_user->check_user_hash_exists($user_hash)) {
			$this->add_error('User hash not found', 'warning');
			return array();
		}


		// 1. Get the user's available balance for spending
		$user_wallet_balance_amt_clovers = $this->get_user_wallet_balance_amt_clovers($user_hash);

		// 2. Get the user's topups
		$query_pending_balance = "SELECT
									SUM(`txn-amt_clovers`) AS `txn-amt_clovers`
								FROM wallet_transactions
								WHERE `txn-hash_user` = :userhash
								AND `txn-status_latest` = 'TXN_PENDING'
								";

		$query_params_pending_balance = array(
			':userhash' => $user_hash,
		);

		try {
			$stmt = $this->db->prepare($query_pending_balance);
			$stmt->execute($query_params_pending_balance);
			$result_pending_balance = $stmt->fetch(PDO::FETCH_ASSOC);
		} catch (PDOException $e) {
			$this->add_error($e->getMessage(), 'error');
			return array();
		}

		// 3. Get the user's withdrawable balance
		$query_withdrawable_balance = "SELECT
										SUM(`txn-amt_clovers`) AS `txn-amt_clovers`
									FROM wallet_transactions
									WHERE `txn-hash_user` = :userhash
									AND `txn-status_latest` = 'TXN_COMPLETED'
									AND `txn-category` != 'topup'
									";

		$query_params_withdrawable_balance = array(
			':userhash' => $user_hash,
		);

		try {
			$stmt = $this->db->prepare($query_withdrawable_balance);
			$stmt->execute($query_params_withdrawable_balance);
			$result_withdrawable_balance = $stmt->fetch(PDO::FETCH_ASSOC);
		} catch (PDOException $e) {
			$this->add_error($e->getMessage(), 'error');
			return array();
		}


		// Return the balance details
		return array(
			'available_balance' => $user_wallet_balance_amt_clovers,
			'pending_balance' => $result_pending_balance['txn-amt_clovers'],
			'withdrawable_balance' => $result_withdrawable_balance['txn-amt_clovers'],
		);
	}


	// Get the user's transaction history
	public function get_transaction_history_by_user_hash($user_hash) {

		// Ensure user hash is valid
		if (!$this->class_user->check_user_hash_exists($user_hash)) {
			$this->add_error('User hash not found', 'warning');
			return array();
		}

		// Get all wallet transactions for the user from the database
		$query = "SELECT
					`txn-hash` AS `txn-hash`,
					`txn-category` AS `txn-category`,
					`txn-amt_clovers` AS `txn-amt_clovers`,
					`txn-amt_USD_cents` AS `txn-amt_USD_cents`,
					`txn-ref_id` AS `txn-ref_id`,
					`txn-status_latest` AS `txn-status_latest`,
					`txn-status_latest_text` AS `txn-status_latest_text`,
					`txn-time_created` AS `txn-time_created`,
					`txn-time_updated` AS `txn-time_updated`,
					`txn-comments` AS `txn-comments`
				FROM wallet_transactions
				WHERE `txn-hash_user` = :userhash
				UNION
				SELECT
					`txn-hash` AS `txn-hash`,
					'topup' AS `txn-category`,
					`txn-amt_clovers` AS `txn-amt_clovers`,
					`txn-amt_USD_cents` AS `txn-amt_USD_cents`,
					`txn-status` AS `txn-status_latest`,
					`txn-status_text` AS `txn-status_latest_text`,
					`txn-time_created` AS `txn-time_created`,
					`txn-time_updated` AS `txn-time_updated`,
					`txn-comments` AS `txn-comments`
				FROM wallet_topups
				WHERE `txn-hash_user` = :userhash
				ORDER BY `txn-time_created` DESC
				";

		// The parameter values
		$query_params = array(
			':userhash' => $user_hash,
		);

		try {
			$stmt = $this->db->prepare($query);
			$stmt->execute($query_params);
			$result = $stmt->fetchAll(PDO::FETCH_ASSOC);
			return $result;
		} catch (PDOException $e) {
			$this->add_error($e->getMessage(), 'error');
			return array();
		}
	}


	// Get transaction details by txn-hash
	public function get_transaction_details_by_txn_hash($txn_hash) {

		// Get the transaction details from the database
		$query = "SELECT
					`txn-hash`,
					`txn-category`,
					`txn-amt_clovers`,
					`txn-ref_id`,
					`txn-status_latest`,
					`txn-status_latest_text`,
					`txn-time_created`,
					`txn-time_updated`,
					`txn-comments`
				FROM wallet_transactions
				WHERE `txn-hash` = :txnhash
				";

		// The parameter values
		$query_params = array(
			':txnhash' => $txn_hash,
		);

		try {
			$stmt = $this->db->prepare($query);
			$stmt->execute($query_params);
			$result = $stmt->fetch(PDO::FETCH_ASSOC);
			return $result;
		} catch (PDOException $e) {
			$this->add_error($e->getMessage(), 'error');
			return array();
		}
	}


	// Attempts to charge the user's wallet for an amount of clovers
	public function attempt_charge_user_wallet($user_hash, $amt_clovers) {

		// Ensure user hash is valid
		if (!$this->class_user->check_user_hash_exists($user_hash)) {
			$this->add_error('User hash not found', 'warning');
			return false;
		}

		// Ensure amt_clovers is valid
		if ($amt_clovers <= 0.00) {
			$this->add_error('Invalid amount of clovers', 'warning');
			return false;
		}

		// Get the user's current wallet balance
		$user_wallet_balance_amt_clovers = $this->get_user_wallet_balance_amt_clovers($user_hash);

		// Ensure the user has enough clovers in their wallet
		if ($user_wallet_balance_amt_clovers < $amt_clovers) {
			$this->add_error('Insufficient clovers in wallet', 'warning');
			return false;
		}
	}


	// Submit withdrawal (cashout) request
	public function submit_withdrawal_request($user_hash, $amt_clovers) {

		// Ensure user hash is valid
		if (!$this->class_user->check_user_hash_exists($user_hash)) {
			$this->add_error('User hash not found', 'warning');
			return false;
		}

		// Ensure amt_clovers is valid
		if ($amt_clovers <= 0.00) {
			$this->add_error('Invalid amount of clovers', 'warning');
			return false;
		}

		// Get the user's withdrawable balance
		$user_wallet_balance_details = $this->get_user_wallet_balance_details($user_hash);
		$user_wallet_withdrawable_balance = $user_wallet_balance_details['withdrawable_balance'];

		// Ensure the user has enough clovers in their wallet
		if ($user_wallet_withdrawable_balance < $amt_clovers) {
			$this->add_error('Insufficient clovers in wallet', 'warning');

			// Insert a failed withdrawal request into the database
			$query_insert_failed_withdrawal = "INSERT INTO wallet_transactions (
													`txn-hash_user`,
													`txn-category`,
													`txn-amt_clovers`,
													`txn-status_latest`,
													`txn-status_latest_text`,
													`txn-comments`
												) VALUES (:userhash, 
												'withdrawal', 
												:amtclovers, 
												'TXN_FAILED', 
												'Withdrawal request failed', 
												'Insufficient clovers in wallet'
												)";

			$query_params_insert_failed_withdrawal = array(
				':userhash' => $user_hash,
				':amtclovers' => $amt_clovers,
			);

			// Execute the query
			try {
				$stmt = $this->db->prepare($query_insert_failed_withdrawal);
				$stmt->execute($query_params_insert_failed_withdrawal);
			} catch (PDOException $e) {
				$this->add_error($e->getMessage(), 'error');
				return false;
			}
			return false;
		}

		// Insert the withdrawal request into the database
		$query_insert_withdrawal = "INSERT INTO wallet_withdrawals (
										`txn-hash_user`,
										`txn-category`,
										`txn-amt_clovers`,
										`txn-status_latest`,
										`txn-status_latest_text`,
										`txn-comments`
				) VALUES (	
					:userhash, 
					:amtclovers, 
					'TXN_PENDING', 
					'Withdrawal request pending', 
					'Withdrawal request submitted'
				)";

		$query_params_insert_withdrawal = array(
			':userhash' => $user_hash,
			':amtclovers' => $amt_clovers,
		);

		// Execute the query
		try {
			$stmt = $this->db->prepare($query_insert_withdrawal);
			$stmt->execute($query_params_insert_withdrawal);
		} catch (PDOException $e) {
			$this->add_error($e->getMessage(), 'error');
			return false;
		}
	}



	// Create a new topup transaction request
	public function create_topup_transaction_request($amt_clovers, $amt_USD_cents, $gateway, $user_hash = null) {
		// If user hash not provided, use the SESSION user hash
		if ($user_hash == null) {
			$user_hash = $_SESSION['user_hash'];
		}
		// If user hash is still null, return false
		if ($user_hash == null) {
			$this->add_error('User hash not found', 'warning');
			return false;
		}

		// The gateway must be supported
		if (!in_array($gateway, SUPPORTED_GATEWAYS)) {
			$this->add_error('Unsupported gateway', 'warning');
			return false;
		}

		// The amount of clovers must be valid
		if ($amt_clovers <= 0.00) {
			$this->add_error('Invalid amount of clovers', 'warning');
			return false;
		}

		// Create new transaction hash
		$txn_hash = 'topup_' . $gateway . '_' . hash('xxh128', uniqid(mt_rand(), true));

		// Insert the transaction request into the database
		$query_insert_topup = "INSERT INTO wallet_topups (
									`txn-hash`,
									`txn-hash_user`,
									`txn-status`,
									`txn-status_text`,
									`txn-amt_clovers`,
									`txn-amt_USD_cents`,
									`txn-gateway`,
									`txn-gateway_response`,
									`txn-gateway_params`,
									`txn-comments`
								) VALUES (
									:txnhash, 
									:userhash, 
									'TXN_PENDING', 
									'Topup request pending', 
									:amtclovers, 
									:amtusd, 
									:gateway, 
									'', 
									'', 
									'')";

		$query_params_insert_topup = array(
			':txnhash' => $txn_hash,
			':userhash' => $user_hash,
			':amtclovers' => $amt_clovers,
			':amtusd' => $amt_USD_cents,
			':gateway' => $gateway,
		);

		// Execute the query
		try {
			$stmt = $this->db->prepare($query_insert_topup);
			$stmt->execute($query_params_insert_topup);
		} catch (PDOException $e) {
			$this->add_error($e->getMessage(), 'error');
			return false;
		}

		// Return the transaction hash
		return $txn_hash;
	}


	// Get the topup details by topup hash
	public function get_topup_details_by_topup_hash($topup_hash) {
		// Get the topup details from the database
		$query = "SELECT * FROM wallet_topups WHERE `txn-hash` = :topuphash";

		// The query params
		$query_params = array(
			':topuphash' => $topup_hash,
		);

		// Execute the query
		try {
			$stmt = $this->db->prepare($query);
			$stmt->execute($query_params);
			$result = $stmt->fetch(PDO::FETCH_ASSOC);

			// If the topup is not found, return false
			if (!$result) {
				return false;
			} else {
				// Return the topup details
				return $result;
			}
		} catch (PDOException $e) {
			$this->add_error($e->getMessage(), 'error');
			return false;
		}
	}


	// Update the txn-gateway_params field in wallet_topups
	public function update_topup_transaction_gateway_params($txn_hash, $txn_gateway_params) {
		$query_topup = "UPDATE wallet_topups
                        SET `txn-gateway_params` = :txn_gateway_params
                        WHERE `txn-hash` = :txn_hash";

		$query_params_topup = array(
			':txn_hash'           => $txn_hash,
			':txn_gateway_params' => $txn_gateway_params
		);

		try {
			$stmt_topup = $this->db->prepare($query_topup);
			$result_topup = $stmt_topup->execute($query_params_topup);
		} catch (PDOException $ex) {
			$this->add_error($ex->getMessage(), 'error');
			return false;
		}

		return $result_topup;
	}

	// Append to the txn-gateway_response (JSON) field in wallet_topups
	public function append_topup_transaction_gateway_response($txn_hash, $message) {
		$query_topup = "SELECT `txn-gateway_response`
                        FROM wallet_topups
                        WHERE `txn-hash` = :txn_hash";

		$query_params_topup = array(
			':txn_hash' => $txn_hash
		);

		try {
			$stmt_topup = $this->db->prepare($query_topup);
			$stmt_topup->execute($query_params_topup);
			$row_topup = $stmt_topup->fetch(PDO::FETCH_ASSOC);
		} catch (PDOException $ex) {
			$this->add_error($ex->getMessage(), 'error');
			return false;
		}

		$txn_gateway_response = json_decode($row_topup['txn-gateway_response'], true);
		$txn_gateway_response[] = array('timestamp' => time(), 'log_text' => $message);

		$query_topup = "UPDATE wallet_topups
                        SET `txn-gateway_response` = :txn_gateway_response
                        WHERE `txn-hash` = :txn_hash";

		$query_params_topup = array(
			':txn_hash'             => $txn_hash,
			':txn_gateway_response' => json_encode($txn_gateway_response)
		);

		try {
			$stmt_topup = $this->db->prepare($query_topup);
			$result_topup = $stmt_topup->execute($query_params_topup);
		} catch (PDOException $ex) {
			$this->add_error($ex->getMessage(), 'error');
			return false;
		}

		return $result_topup;
	}

	// Update the txn-status and txn-status_text fields in wallet_topups
	public function update_topup_transaction_status($txn_hash, $txn_status, $txn_status_text) {
		$query_topup = "UPDATE wallet_topups
                        SET `txn-status` = :txn_status,
                            `txn-status_text` = :txn_status_text
                        WHERE `txn-hash` = :txn_hash";

		$query_params_topup = array(
			':txn_hash'      => $txn_hash,
			':txn_status'    => $txn_status,
			':txn_status_text' => $txn_status_text
		);

		try {
			$stmt_topup = $this->db->prepare($query_topup);
			$result_topup = $stmt_topup->execute($query_params_topup);
		} catch (PDOException $ex) {
			$this->add_error($ex->getMessage(), 'error');
			return false;
		}

		if ($result_topup) {
			return $this->append_topup_transaction_gateway_response($txn_hash, "Transaction status updated to: " . $txn_status_text);
		} else {
			return false;
		}
	}

	// User aborted the payment process, mark the payment as USER_CANCELLED
	public function user_aborted_payment($txn_hash) {
		$update_status = $this->update_topup_transaction_status($txn_hash, 'USER_CANCELLED', 'User aborted payment process');
		return $update_status !== false;
	}
}
